version: '2.2'
services:
  web:
    build:
      context: ./nginx
    image: ${NGINX_IMAGE_NAME}:v1
    environment:
      - FASTCGI_PASS_HOST=php
    ports:
      - '${NGINX_HOST_HTTP_PORT}:80'
    volumes:
      # Application
      - ${CODE_PATH_LOCAL}:${CODE_PATH_DIST}:delegated
      # Nginx
      - ./nginx/conf/conf.d:/etc/nginx/conf.d:delegated
      - ./nginx/log:/var/log/nginx:delegated
    depends_on:
        - php
    networks:
      - backend
