version: '2.2'
services:
  web:
    build:
      context: ./nginx
    image: local/phundament/nginx-one
    environment:
      - FASTCGI_PASS_HOST=php
    ports:
      - '80:80'
    volumes:
      # Application testing
      - ..:/app/web:delegated
      - ./nginx/conf/conf.d:/etc/nginx/conf.d:delegated
      - ./nginx/log:/var/log/nginx:delegated
    depends_on:
        - php
    networks:
      - backend
